CREATE TABLE third_party_tokens
(
    token_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_value VARCHAR(255)                NOT NULL UNIQUE,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(255)
);
